export type Product = {
  slug: string;
  name: string;
  category: "women" | "men" | "accessories";
  type: string;
  price: number;
  colors: string[];
  sizes: string[];
  images: string[];
  materials: string;
  description: string;
  tag?: "new" | "low";
};

export const products: Product[] = [
  {
    slug: "noir-oversized-blazer",
    name: "Oversized Blazer",
    category: "women",
    type: "outerwear",
    price: 890,
    colors: ["#0D0D0D", "#C4B59B"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: ["p-blazer-1.jpg", "p-blazer-2.jpg"],
    materials: "100% organic wool · GOTS certified · Made in Portugal",
    description: "An oversized double-breasted blazer cut from Italian organic wool. Structured shoulders, relaxed body, half-lined in silk. Intended to be worn for a decade.",
    tag: "new",
  },
  {
    slug: "silk-camisole",
    name: "Silk Camisole",
    category: "women",
    type: "tops",
    price: 320,
    colors: ["#E4DDD0", "#0D0D0D"],
    sizes: ["XS", "S", "M", "L"],
    images: ["p-camisole-1.jpg", "p-camisole-2.jpg"],
    materials: "100% mulberry silk · Certified GOTS · Made in Italy",
    description: "A bias-cut silk camisole with adjustable straps. Finished with French seams and a hand-rolled hem.",
  },
  {
    slug: "wide-leg-trouser",
    name: "Wide-Leg Trouser",
    category: "women",
    type: "bottoms",
    price: 490,
    colors: ["#0D0D0D", "#6B6256"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: ["p-trousers-1.jpg", "p-trousers-2.jpg"],
    materials: "Organic wool crêpe · Lined in cupro · Made in Portugal",
    description: "High-rise, wide-leg trousers in an Italian wool crêpe. Crisp but not stiff. Lined to the knee.",
    tag: "low",
  },
  {
    slug: "column-dress",
    name: "Column Dress",
    category: "women",
    type: "dresses",
    price: 780,
    colors: ["#0D0D0D"],
    sizes: ["XS", "S", "M", "L"],
    images: ["p-dress-1.jpg", "p-dress-2.jpg"],
    materials: "Bio-based viscose · OEKO-TEX certified · Made in Italy",
    description: "A floor-length column dress with a bateau neckline. Structured in the bodice, fluid in the skirt.",
  },
  {
    slug: "linen-shirt-dress",
    name: "Linen Shirt Dress",
    category: "women",
    type: "dresses",
    price: 420,
    colors: ["#E4DDD0", "#C4B59B"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: ["p-shirtdress-1.jpg", "p-shirtdress-2.jpg"],
    materials: "100% European linen · Made in Portugal",
    description: "A relaxed shirt dress in heavyweight linen. Dropped shoulders, tortoise buttons, belt included.",
  },
  {
    slug: "merino-crewneck",
    name: "Merino Crewneck",
    category: "men",
    type: "knitwear",
    price: 380,
    colors: ["#0D0D0D", "#E4DDD0", "#6B6256"],
    sizes: ["S", "M", "L", "XL"],
    images: ["p-knit-1.jpg", "p-knit-2.jpg"],
    materials: "100% Italian merino wool · Mulesing-free · Made in Italy",
    description: "A mid-weight merino crewneck. Fine gauge, ribbed at cuffs and hem, slightly relaxed through the body.",
    tag: "new",
  },
  {
    slug: "relaxed-chino",
    name: "Relaxed Chino",
    category: "men",
    type: "bottoms",
    price: 340,
    colors: ["#C4B59B", "#0D0D0D"],
    sizes: ["S", "M", "L", "XL"],
    images: ["p-chinos-1.jpg", "p-chinos-2.jpg"],
    materials: "Organic cotton twill · Made in Portugal",
    description: "A relaxed-fit chino in heavyweight organic cotton twill. Straight leg, single pleat, leather-trimmed belt loops.",
  },
  {
    slug: "cotton-overshirt",
    name: "Cotton Overshirt",
    category: "men",
    type: "outerwear",
    price: 490,
    colors: ["#6B6256", "#0D0D0D"],
    sizes: ["S", "M", "L", "XL"],
    images: ["p-overshirt-1.jpg", "p-overshirt-2.jpg"],
    materials: "Heavy cotton canvas · Corozo buttons · Made in Portugal",
    description: "A boxy cotton overshirt in washed canvas. Two chest pockets, horn buttons, unlined.",
    tag: "low",
  },
  {
    slug: "leather-tote",
    name: "Grain Leather Tote",
    category: "accessories",
    type: "bags",
    price: 1200,
    colors: ["#0D0D0D", "#6B6256"],
    sizes: ["ONE"],
    images: ["p-tote-1.jpg", "p-tote-2.jpg"],
    materials: "Vegetable-tanned Italian leather · Brass hardware · Made in Florence",
    description: "An unlined grain leather tote that softens with age. Fits a 15\" laptop. Hand-finished in Florence.",
    tag: "new",
  },
  {
    slug: "cashmere-scarf",
    name: "Cashmere Scarf",
    category: "accessories",
    type: "scarves",
    price: 260,
    colors: ["#E4DDD0", "#0D0D0D", "#6B6256"],
    sizes: ["ONE"],
    images: ["p-scarf-1.jpg", "p-scarf-2.jpg"],
    materials: "100% Mongolian cashmere · Hand-fringed · Made in Scotland",
    description: "A lightweight cashmere scarf, woven in Scotland. Generously sized, hand-fringed edges.",
  },
  {
    slug: "card-holder",
    name: "Leather Card Holder",
    category: "accessories",
    type: "small-leather",
    price: 140,
    colors: ["#0D0D0D", "#6B6256"],
    sizes: ["ONE"],
    images: ["p-cardholder-1.jpg", "p-cardholder-2.jpg"],
    materials: "Full-grain Italian leather · Made in Florence",
    description: "A slim card holder in vegetable-tanned leather. Holds six cards and a few folded notes.",
  },
  {
    slug: "shoulder-bag",
    name: "Structured Shoulder Bag",
    category: "accessories",
    type: "bags",
    price: 890,
    colors: ["#0D0D0D"],
    sizes: ["ONE"],
    images: ["p-shoulder-1.jpg", "p-shoulder-2.jpg"],
    materials: "Smooth Italian calfskin · Brass hardware · Made in Florence",
    description: "A compact structured bag in smooth calfskin. Fits a phone, a wallet, and a small notebook.",
  },
];

export const categories = [
  { slug: "women", label: "Women" },
  { slug: "men", label: "Men" },
  { slug: "accessories", label: "Accessories" },
] as const;
